import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/reactQueryProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased justify-center items-center flex min-h-screen`}
          >
          <SessionProvider session={session}>
            <ReactQueryClientProvider>
              <Toaster />
              {children}
            </ReactQueryClientProvider>
          </SessionProvider>
        </body>
      </html>
  );
}
